export const SELECTED_FACILITY_REFINE_MAJOR_TYPES = {
  HOME_CARE_SERVICE: "HOME_CARE_SERVICE",
  FACILITY_SERVICE: "FACILITY_SERVICE",
  MEDICAL_CARE_SERVICE: "MEDICAL_CARE_SERVICE",
  WELFARE_SERVICE: "WELFARE_SERVICE",
  ALL: "ALL",
} as const;

export const SELECTED_HOME_CARE_MIDDLE_TYPES = {
  HOME_VISIT_NURSING: "HOME_VISIT_NURSING",
  HOME_CARE_SUPPORT_SERVICE: "HOME_CARE_SUPPORT_SERVICE",
  COMMUNITY_GENERAL_SUPPORT_CENTER: "COMMUNITY_GENERAL_SUPPORT_CENTER",
} as const;

export const SELECTED_MEDICAL_CARE_MIDDLE_TYPES = {
  HOME_VISIT_CLINIC: "HOME_VISIT_CLINIC",
  HOSIPITAL: "HOSIPITAL",
  HOME_VISIT_DENTAL_CLINIC: "HOME_VISIT_DENTAL_CLINIC",
  HOME_VISIT_PHARMACY: "HOME_VISIT_PHARMACY",
  CLINIC: "CLINIC",
} as const;

export const SELECTED_FACILITY_MIDDLE_TYPES = {
  GENERAL_ELDERLY_HOUSE: "GENERAL_ELDERLY_HOUSE",
  GENERAL_WITH_CARE_ELDERLY_HOUSE: "GENERAL_WITH_CARE_ELDERLY_HOUSE",
  GENERAL_WITH_SERVICE_ELDERLY_HOUSE: "GENERAL_WITH_SERVICE_ELDERLY_HOUSE",
  LONG_TERM_CARE_ELDERLY_FACILITY: "LONG_TERM_CARE_ELDERLY_FACILITY",
  LONG_TERM_CARE_HEALTH_FACILITY: "LONG_TERM_CARE_HEALTH_FACILITY",
} as const;

export const CURRENT_MIDDLE_TYPE = {
  HOME_VISIT_NURSING: "HOME_VISIT_NURSING",
  HOME_CARE_SUPPORT_SERVICE: "HOME_CARE_SUPPORT_SERVICE",
  COMMUNITY_GENERAL_SUPPORT_CENTER: "COMMUNITY_GENERAL_SUPPORT_CENTER",
  HOME_VISIT_CLINIC: "HOME_VISIT_CLINIC",
  HOSIPITAL: "HOSIPITAL",
  HOME_VISIT_DENTAL_CLINIC: "HOME_VISIT_DENTAL_CLINIC",
  HOME_VISIT_PHARMACY: "HOME_VISIT_PHARMACY",
  CLINIC: "CLINIC",
  GENERAL_ELDERLY_HOUSE: "GENERAL_ELDERLY_HOUSE",
  GENERAL_WITH_CARE_ELDERLY_HOUSE: "GENERAL_WITH_CARE_ELDERLY_HOUSE",
  GENERAL_WITH_SERVICE_ELDERLY_HOUSE: "GENERAL_WITH_SERVICE_ELDERLY_HOUSE",
  LONG_TERM_CARE_ELDERLY_FACILITY: "LONG_TERM_CARE_ELDERLY_FACILITY",
  LONG_TERM_CARE_HEALTH_FACILITY: "LONG_TERM_CARE_HEALTH_FACILITY",
  ALL: "ALL",
} as const;

export const DISPLAY_CURRENT_MIDDLE_TYPE_MAP = {
  HOME_VISIT_NURSING: "訪問看護ステーション",
  HOME_CARE_SUPPORT_SERVICE: "居宅介護支援",
  COMMUNITY_GENERAL_SUPPORT_CENTER: "地域包括支援センター",
  HOME_VISIT_CLINIC: "訪問診療",
  HOSIPITAL: "病院",
  HOME_VISIT_DENTAL_CLINIC: "訪問歯科",
  HOME_VISIT_PHARMACY: "訪問薬局",
  CLINIC: "クリニック",
  GENERAL_ELDERLY_HOUSE: "住宅型有料老人ホーム",
  GENERAL_WITH_CARE_ELDERLY_HOUSE: "介護付き有料老人ホーム",
  GENERAL_WITH_SERVICE_ELDERLY_HOUSE: "サービス付き高齢者住宅",
  LONG_TERM_CARE_ELDERLY_FACILITY: "特別養護老人ホーム",
  LONG_TERM_CARE_HEALTH_FACILITY: "老人保健施設",
  ALL: "全て",
} as const;

export const DISPLAY_CURRENT_MAJOR_TYPE_MAP = {
  HOME_CARE_SERVICE: "居宅サービス",
  FACILITY_SERVICE: "施設サービス",
  MEDICAL_CARE_SERVICE: "医療サービス",
  WELFARE_SERVICE: "福祉サービス",
  ALL: "全て",
} as const;

export const HOME_CARE_MIDDLE_TYPES_CHECKBOX_ITEMS = [
  { label: "居宅介護支援事業所", value: "HOME_CARE_SUPPORT_SERVICE" },
  { label: "地域包括支援センター", value: "COMMUNITY_GENERAL_SUPPORT_CENTER" },
  { label: "訪問看護ステーション", value: "HOME_VISIT_NURSING" },
] as const;
export const MEDICAL_MIDDLE_TYPES_CARE_CHECKBOX_ITEMS = [
  { label: "訪問診療", value: "HOME_VISIT_CLINIC" },
  { label: "訪問歯科", value: "HOME_VISIT_DENTAL_CLINIC" },
  { label: "訪問薬局", value: "HOME_VISIT_PHARMACY" },
  { label: "診療所", value: "CLINIC" },
  { label: "病院", value: "HOSIPITAL" },
] as const;
export const FACILITY_CARE_MIDDLE_TYPES_CHECKBOX_ITEMS = [
  { label: "住宅型有料老人ホーム", value: "GENERAL_ELDERLY_HOUSE" },
  { label: "サ高住", value: "GENERAL_WITH_SERVICE_ELDERLY_HOUSE" },
  { label: "介護付き有料老人ホーム", value: "GENERAL_WITH_CARE_ELDERLY_HOUSE" },
  { label: "老人保健施設", value: "LONG_TERM_CARE_ELDERLY_FACILITY" },
  { label: "特別養護老人ホーム", value: "LONG_TERM_CARE_HEALTH_FACILITY" },
] as const;
